apiVersion: dummy.dwk.dummy.dwk/v1
kind: DummySite
metadata:
  labels:
    app.kubernetes.io/name: dummy-controller
    app.kubernetes.io/managed-by: kustomize
  name: dummysite-sample
spec:
  # TODO(user): Add fields here
