apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-pings
          persistenVolumeClaim:
            claimName: pings-claim
      containers:
        - name: ping-pong
          image: desipeli/dwk-pingpong:0.2
          volumeMounts:
          - name: shared-pings
            mountPath: /app/files/shared
          env:
          - name: PORT
            value: "8002"