apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
- manifests/ingress.yaml
- manifests/init-sql.yaml
- manifests/postgres.yaml
- manifests/service.yaml
images:
- name: PINGPONG/IMAGE
  newName: desipeli/dwk-pingpong
  newTag: ea847eb28def8be9fbf146a455fd14db631ae496
