apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/init-sql.yaml
  - manifests/postgres.yaml
  - manifests/service.yaml
images:
  - name: PINGPONG/IMAGE
    newName: desipeli/dwk-pingpong:3.02