apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./analysistemplate.yaml
  - ./ingress.yaml
  - ./secret.yaml
  - broadcaster/manifests/deployment.yaml
  - broadcaster/manifests/service.yaml
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/persistentvolume.yaml
  - todo-app/manifests/persistentvolumeclaim.yaml
  - todo-app/manifests/service-app.yaml
  - todo-backend/manifests/daily-todo-cron.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/init-sql.yaml
  - todo-backend/manifests/postgres-todo.yaml
  - todo-backend/manifests/service-backend.yaml
images:
  - name: TODOAPP/IMAGE
    newName: desipeli/dwk-todo-app:4.05v3
  - name: TODOBACKEND/IMAGE
    newName: desipeli/dwk-todo-backend:4.06
  - name: TODOBROADCASTER/IMAGE
    newName: desipeli/dwk-broadcaster:4.06