apiVersion: v1
kind: Secret
metadata:
    name: todo-database-secret
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:f0nUWDzh6FehFLNa,iv:3QuFK9YLAsc+7OhdcnBgZ/4VUvPkZLa38AuRAOq/+zY=,tag:lqn8+6xLkH5LPmJ5LqVs8w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:agAzfWqBbaf/+YwmXEtuPoHKXLRsWsKc/T4jnttNLBflD5osu6fkYembX7jv5rFwnZvXZSsC6WXMDR6qxVjXeQ==,iv:R8cOiQ9PaFKdDG1T4nd1XRmUV5rVNElIGb25VubVn4o=,tag:jLzuCNPSDF7JtLQymsIeqg==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:HAe7SFaDQ2DN0PxSJrsI7o5brf22cF5C6hFk2JgTcWU986KwPQuvK6iuffsKypgRpv3egw/f44ydQWu5jtW+Q+7GCdD/++WtKm2Q/vOit5/nkEy4q/gIl13BZ8QLg5yEXNd0rK9h+wmDLG4eM4HY7BP7g0p+YG/qIZ5Kt376Z0w8HM7q3xzGkChLncqblbF+Aldo41IdGvzEQCNVDR8hIiGpMC0=,iv:PRAzm0n5JFX6jMpvDNCdH17lNgoJDDnWNK2RYr+J0xk=,tag:jymLCb7vVzQbHXTrhTqqxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mcxnf7uc4vwame00e36s9u5znc4lztxccg67fp223nrkk8yntq8qn96n3t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYlhLYnZpZ0lzOUw1Y29V
            aDdjN3lMdTY1a3o2TU5QOXNjVG40d0NxMTF3CmJxNW5la3pFdEZxVU93K25ieFM3
            MVEvRi9FbWl3LzE2M0dCUUJCcUxraG8KLS0tIGhQNXZncTVleVhxK0pwUmZnSFFm
            R29jcW5MTkttQzhUb0xFL3FlTk5oUVkKEU53Tq8ESazpkB0K1B8EYrVdDOnoLKcL
            qf0enSaBv+JB6YGpgyj5+wYruHaZclm+UitkkxLxqC2ynA1RSp7Ywg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T11:32:40Z"
    mac: ENC[AES256_GCM,data:ETH1RmjHoU/AwjWVr/ek0gFARl6RZssmBSx+0jjvuDR6JEIxleR22ZS5WCL66RLFgaShg1Yw3BISW0vNAKhcDaRqzL25dlj79RFfW7h5pSIzk7vQmrdoDQTqcLoXhNYvlxWFFsY4C9Snqit02Svbtwjt8xnOUhjuAKXWIEHh9hM=,iv:q9DhbGvk46gOrdJvQZmkruxSbUfXcbWLE4kEaOtESyg=,tag:/JlVVvUqnHehTzrddYc5FQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
