apiVersion: apps/v1
kind: Deployment
metadata:
  name: logpod-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logpod
  template:
    metadata:
      labels:
        app: logpod
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: log-writer
          image: desipeli/dwk-log-writer:0.11
          volumeMounts:
          - name: shared-logs
            mountPath: /app/files
        - name: log-reader
          image: desipeli/dwk-log-reader:0.11
          volumeMounts:
          - name: shared-logs
            mountPath: /app/files
          env:
          - name: PORT
            value: "8001"