apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS pings (
      id SERIAL PRIMARY KEY,
      pongs INTEGER
    );
    INSERT INTO pings (pongs) VALUES (0);
