apiVersion: v1
kind: Secret
metadata:
    name: todo-database-secret
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:mK9AChpx5lxpx1Eq,iv:bMOQn6aN9U2DFU5zoQc+NKbNoZTqpT4ba4jlo+o7wJ8=,tag:GHTBZRrofCBPVPst+U2hcw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:cwHqTLoBSwF+Dh9QSMQFGe4Mao3FFRAiStqy8izkU75ytRoorB91GRIpkaBg4crJZEd/9xMlDvGKSkN5nGqDwQ==,iv:WeBfcUjIxsqmWjF1qN5OXugPut+JooktIp8r2tyc7xA=,tag:zKRDGP7rWUaq84fhLE3grw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mcxnf7uc4vwame00e36s9u5znc4lztxccg67fp223nrkk8yntq8qn96n3t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaVZiNW1GZFVxbDB5eVE5
            Zk1PaENwaTB4ZHNkZ2YzKzZBNXhXRFRPZGtBCmJoNnRtNkdDSnEwVlY4ZFNJd3ln
            dVNEd3oraWZSQ3lwTGdlOGx5czQxMGMKLS0tIElRMm1xcUwwdWJpUzIza3hFVVYw
            NzVWMHJUdkpndThNcHdHZ3pxRTZuYUkKlKzeM55YkxvNxHuGxPFODcn4QX9wTE30
            tPUuHWVj0kftf/aW1WJmFpeNQ6TG3xsLWbsBw6Oj2qlASdXjBeI3RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-02T12:02:23Z"
    mac: ENC[AES256_GCM,data:ZmidulCDyCeRIfSsnounQ13MvNqDXpzCeJcpaz/2jG2Ef99eTqm+6MhY0LZQrtxrveD+HrznHmiDXvHSxYm6RFZ40kj5U0hADAtNzVPoWTFlQ3Q+Iw8kSZyysuoEMKDGbKik0Ntr8CV1x2wLfuV1mB1irLaXALOqFQpeffyJzMU=,iv:FQtE9zE7vauP91qfcbi3Sebg6sckafDojc6FT1KKEYE=,tag:ilK+m1D1iUZVAI5Sk5Nr4w==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
