apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: desipeli/dwk-pingpong:2.07
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "8002"
          envFrom:
            - secretRef:
                name: ping-database-secret