name: Build and publish broadcaster

on:
  push:
    paths:
      - todo/broadcaster/**

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo/broadcaster

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and publish broadcaster
        run: |-
          docker build -t "desipeli/dwk-broadcaster:$GITHUB_SHA" .
          docker push "desipeli/dwk-broadcaster:$GITHUB_SHA"

      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: desipeli/dwk-gitops
          token: ${{ secrets.PAT }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update staging conf
        if: github.ref_type == 'branch'
        working-directory: ./broadcaster/overlays/staging
        run: kustomize edit set image TODOBROADCASTER/IMAGE=desipeli/dwk-broadcaster:$GITHUB_SHA
      
      - name: commit staging kustomization.yaml to GitHub
        if: github.ref_type == 'branch'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'broadcaster/overlays/staging/kustomization.yaml'
          message: New version released ${{ github.sha }}

      - name: Update production conf
        if: github.ref_type == 'tag'
        working-directory: ./broadcaster/overlays/production
        run: kustomize edit set image TODOBROADCASTER/IMAGE=desipeli/dwk-broadcaster:$GITHUB_SHA
      
      - name: commit production kustomization.yaml to GitHub
        if: github.ref_type == 'tag'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'broadcaster/overlays/production/kustomization.yaml'
          message: New version released ${{ github.ref_name }}