name: Build and publish ping-pong

on:
  push:
    paths:
      - ping-pong/**

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      
      - name: Build and publish ping-pong
        run: |-
          docker build -t "desipeli/dwk-pingpong:$GITHUB_SHA" ping-pong/
          docker push "desipeli/dwk-pingpong:$GITHUB_SHA"
      
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: kustomize edit set image PINGPONG/IMAGE=desipeli/dwk-pingpong:$GITHUB_SHA
      
      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'ping-pong/kustomization.yaml'
          message: New version released ${{ github.sha }}