name: deploy dockerhub
on:
  push:
    branches:
      - main
    paths:
      - 'todo-app/**'
jobs:

  deploy-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: ./todo-app
          push: true
          tags: desipeli/dwk-todo-app:latest